server:
  servlet:
    contextPath: /api
  port: '8082'
spring:
  jpa:
    database: postgresql
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    password: '123'
    driver-class-name: org.postgresql.Driver
    generate-unique-name: 'false'
    username: danialedilev
    initialization-mode: ALWAYS
    schema: classpath*:db/initDB.sql
    url: jdbc:postgresql://localhost:5432/intc
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

jwt:
  secret: mySecr3t!

#  spring.datasource.url=jdbc:postgresql://localhost:5432/intc
#  spring.datasource.username=danialedilev
#  spring.datasource.password=123
#  server.servlet.contextPath=/api
#  spring.datasource.generate-unique-name=false
#  spring.jpa.show-sql=true
#  spring.datasource.driver-class-name=org.postgresql.Driver
#  spring.jpa.database=postgresql
#  spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
#  spring.datasource.initialization-mode=ALWAYS
#  spring.datasource.schema=classpath*:db/initDB.sql
#  server.port=8082
#  logging.level.org.hibernate.SQL=DEBUG
#  logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
##spring.datasource.data=classpath*:db/populateDB.sql